export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const AUTENTICATE_USER_SUCCESS = 'AUTENTICATE_USER_SUCCESS';
export const AUTENTICATE_USER_FAILURE = 'AUTENTICATE_USER_FAILURE';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_FAILURE';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
